/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        final Logger logger = LogManager.getLogger(App.class);
        System.out.println(new App().getGreeting());
        logger.debug("logging tests");
    }
}
